# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# Default values for arvados.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# The external IP address for this Arvados cluster.
# Must be set to a valid IP address, e.g. by using --set when invoking helm
externalIP: ~

# The default e-mail address and password for the initial cluster admin user
adminUserEmail: "test@example.com"
adminUserPassword: "passw0rd"

# A super user token
superUserSecret: "thisisnotaverygoodsuperusersecretstring00000000000"
# An anonymous user token
anonymousUserSecret: "thisisnotaverygoodanonymoussecretstring00000000000"

# The package versions for this Arvados cluster. Also see
#
#   curl http://versions.arvados.org/v1/commit/ | jq .
#
arvados:
  versions:
    distribution:
      arvadosApiServer: 1.1.4.20180611193222*
      arvadosGitHttpd: 1.1.4.20180605191011*
      arvadosHealth: 1.1.4.20180605191011*
      arvadosWorkbench: 1.1.4.20180605195657*
      arvadosWs: 1.1.4.20180605191011*
      arvadosSSOServer: 0.1.20171122141118.ba584a7*
      crunchDispatchSlurm: 1.1.4.20180605191011*
      crunchRun: 1.1.4.20180605191011*
      crunchRunner: 1.1.4.20180605191011*
      keepBalance: 1.1.4.20180607192404*
      keepStore: 1.1.4.20180605191011*
      keepWeb: 1.1.4.20180605191011*
      keepProxy: 1.1.4.20180605191011*
      libPamArvados: 1.1.4.20180404223512*
      pythonArvadosFuse: 1.1.4.20180604132029*
      pythonArvadosPythonClient: 1.1.4.20180607152043*
    gem:
      arvados: 1.1.4.20180412190507
      arvadosCLI: 1.1.4.20180412190507
      arvadosLoginSync: 1.1.4.20180424214444
